if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

alias ls="ls -a --color=auto"
alias mkenter="source mkenter"

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh